# -*- coding: utf-8 -*-
"""💉DiaDecode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIinW-0AJkrgbuFnFALAZzB00keWCYIT

#**📖 Introduction**
---
The Pima Indians Diabetes Dataset is a widely adopted benchmark in healthcare analytics and machine learning, collected by the National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK). This dataset enables prediction of diabetes likelihood based on simple but meaningful diagnostic measurements.

The records represent female patients of Pima Indian descent, aged 21 and older, with routine medical variables captured during checkups:

| Feature                        | Description                                   |
| ------------------------------ | --------------------------------------------- |
| **Pregnancies**                | Number of times pregnant                      |
| **Glucose**                    | Plasma glucose concentration (2-hour OGTT)    |
| **Blood Pressure**             | Diastolic blood pressure (mm Hg)              |
| **Skin Thickness**             | Triceps skinfold thickness (mm)               |
| **Insulin**                    | 2-Hour serum insulin (µU/ml)                  |
| **BMI**                        | Body Mass Index (kg/m²)                       |
| **Diabetes Pedigree Function** | Genetic risk estimate based on family history |
| **Age**                        | Patient’s age in years                        |
| **Outcome (Target)**           | 1 = Diabetic, 0 = Non-Diabetic                |

---
#**Why This Dataset Matters**

* Practical relevance: Targets real-world healthcare needs by facilitating early diabetes detection.

* Balanced complexity: Blends demographic, physiological, and genetic variables—ideal for both exploratory data analysis and model building.

* Manageable size: With 768 records and 8 features, the dataset is small enough for beginners yet rich in potential insights.

---

#**Project Overview**

---
In this notebook, we will:

Clean and preprocess the data (handle zero-value outliers, standardize metrics).

Perform Exploratory Data Analysis (EDA)—identify patterns, outliers, and correlations.

Train and evaluate machine learning models to determine which factors are most predictive of diabetes risk.

This structured, hands-on exploration will illustrate how data-driven methods can support clinical decision-making and healthcare analytics.

---

#**Explore AI-Powered Diabetes Coaching**
---

Besides traditional data analysis, this project connects with cutting-edge AI tools.
Check out AI Dia Coach — an intuitive web-based app offering interactive diabetes risk assessment and personalized health guidance:

Open the preview: (https://preview--ai-dia-coach.lovable.app/)

Use this tool alongside the dataset exploration to see how real-time AI insights can complement traditional statistical and ML approaches in healthcare.

#**⚡ Powering Up the Toolbox**


---
"""

# Pandas → For handling and analyzing structured data (tables, CSVs, etc.)
# Matplotlib → For creating basic plots and data visualizations
# Seaborn → For advanced, stylish, and statistical visualizations (built on Matplotlib)
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""In this step, we load the essential Python libraries required for data analysis and visualization:

- **🐼 pandas**  
  - A powerful library for **data manipulation** and **analysis**.  
  - Provides DataFrame and Series objects for handling structured data.  
  - Commonly used for loading, cleaning, transforming, and summarizing datasets.  

- **📊 matplotlib**  
  - The most widely used **data visualization** library in Python.  
  - Allows creation of **static, interactive, and animated** plots.  
  - Highly customizable for different chart types (line, bar, scatter, histogram, etc.).  

- **🎨 seaborn**  
  - A high-level visualization library built on top of **matplotlib**.  
  - Makes it easy to create **aesthetic and informative** statistical graphics.  
  - Comes with **built-in themes, color palettes, and statistical plot types**.  


# **Importing core libraries for analysis & visualization**

---
import pandas as pd       # Data handling & analysis

import matplotlib.pyplot as plt  # Base visualization library

import seaborn as sns     # Advanced visualization library

# **Optional: Set a beautiful seaborn style for all plots**

---
sns.set_theme(style="whitegrid")

#**📥 Bringing Data Onboard**
---
"""

# Reading the diabetes.csv file into a Pandas DataFram
df = pd.read_csv('/content/diabetes csv')

# Displaying the DataFrame to get a quick look at the dataset
df

"""#**✨ Explanation**
---
* 📂 Loading the dataset – We use pd.read_csv() from Pandas to read the diabetes.csv file into a DataFrame.

* 🧾 DataFrame (df) – Think of it as a smart spreadsheet in Python. It holds the dataset in rows and columns, making it easy to analyze.

* 👀 Displaying df – Simply typing df shows the first few and last few rows of the dataset, giving us a quick preview of the data we’re working with.

✅ This step sets the foundation for all further analysis, since now the dataset is structured and ready to explore.

#**🔎 Sneak Peek Into the Data**
---
"""

# ✅ Display the first 5 rows of the dataset
#    Helps us quickly glance at how the dataset looks like
df.head()

# ✅ Display the last 5 rows of the dataset
# Useful to see how data is structured at the end
df.tail()

# ✅ General info about dataset
# Includes column names, data types, and missing values
df.info()

# ✅ Data types of each column
# Useful to know which features are numeric, categorical, string, etc.
df.dtypes

# ✅ Statistical summary of numerical features
# Mean, median, min, max, standard deviation, etc.
df.describe()

# ✅ Columns present in dataset
# Lets us see all features/variables available for analysis
df.columns

# ✅ Shape of dataset (rows, columns)
#    Tells us dataset size – how many records (rows) and features (columns)
df.shape

"""#**🩺 Pima DiabetesX (Health-based Prediction Dataset)**
**📊 Dataset Preview**

---

The Pima Indians Diabetes dataset contains diagnostic health records of female patients of Pima Indian heritage.
The goal is to predict whether a patient has diabetes (1) or not (0).

| Pregnancies | Glucose | BloodPressure | SkinThickness | Insulin | BMI  | DiabetesPedigreeFunction | Age | Outcome |
| ----------- | ------- | ------------- | ------------- | ------- | ---- | ------------------------ | --- | ------- |
| 6           | 148     | 72            | 35            | 0       | 33.6 | 0.627                    | 50  | 1       |
| 1           | 85      | 66            | 29            | 0       | 26.6 | 0.351                    | 31  | 0       |
| 8           | 183     | 64            | 0             | 0       | 23.3 | 0.672                    | 32  | 1       |
| 1           | 89      | 66            | 23            | 94      | 28.1 | 0.167                    | 21  | 0       |
| 0           | 137     | 40            | 35            | 168     | 43.1 | 2.288                    | 33  | 1       |

#**🔹 Observations**

* Pregnancies: Number of times the patient was pregnant.

* Glucose: Plasma glucose concentration (mg/dL).

* BloodPressure: Diastolic blood pressure (mm Hg).

* SkinThickness: Triceps skin fold thickness (mm).

* Insulin: 2-Hour serum insulin (mu U/ml).

* BMI: Body Mass Index.

* DiabetesPedigreeFunction: Genetic risk score.

* Age: Patient’s age.

* Outcome: Target variable → 1 = Diabetic, 0 = Non-Diabetic.

✨ This table shows a mix of medical test results and demographic details used to predict diabetes.

---

#**📊 Dataset Tail (df.tail())**
---
The last 5 rows of the Pima Indians Diabetes dataset:

| Pregnancies | Glucose | BloodPressure | SkinThickness | Insulin | BMI  | DiabetesPedigreeFunction | Age | Outcome |
| ----------- | ------- | ------------- | ------------- | ------- | ---- | ------------------------ | --- | ------- |
| 10          | 101     | 76            | 48            | 180     | 32.9 | 0.171                    | 63  | 0       |
| 2           | 122     | 70            | 27            | 0       | 36.8 | 0.340                    | 27  | 0       |
| 5           | 121     | 72            | 23            | 112     | 26.2 | 0.245                    | 30  | 0       |
| 1           | 126     | 60            | 0             | 0       | 30.1 | 0.349                    | 47  | 1       |
| 1           | 93      | 70            | 31            | 0       | 30.4 | 0.315                    | 23  | 0       |

#**📝 Insights from df.tail()**
* Even the last rows maintain consistent structure (no missing columns).

* Some Insulin values are 0, which may indicate missing or unrecorded data.

* The Outcome column still shows both diabetic (1) and non-diabetic (0) cases at the end of the dataset.

---

#**📊 Overview**
---

The Pima Indians Diabetes dataset has 768 rows and 9 columns.
All columns are numeric, which makes it suitable for statistical analysis and machine learning.

| # | Column Name                  | Non-Null Count | Data Type | Notes             |
| - | ---------------------------- | -------------- | --------- | ----------------- |
| 0 | **Pregnancies**              | 768 non-null   | int64     | No missing values |
| 1 | **Glucose**                  | 768 non-null   | int64     | No missing values |
| 2 | **BloodPressure**            | 768 non-null   | int64     | No missing values |
| 3 | **SkinThickness**            | 768 non-null   | int64     | No missing values |
| 4 | **Insulin**                  | 768 non-null   | int64     | No missing values |
| 5 | **BMI**                      | 768 non-null   | float64   | No missing values |
| 6 | **DiabetesPedigreeFunction** | 768 non-null   | float64   | No missing values |
| 7 | **Age**                      | 768 non-null   | int64     | No missing values |
| 8 | **Outcome (Target)**         | 768 non-null   | int64     | No missing values |

#**📝 Key Insights**

* ✅ No missing values are detected in the dataset.

* 📊 7 integer columns and 2 float columns.

* 🧮 The dataset is memory-efficient (≈54 KB).

* 🎯 Target variable: Outcome (0 = Non-Diabetic, 1 = Diabetic).

---
#**📊 Data Types of Columns**
---
The dataset contains 9 columns with the following data types:

| **Column Name**           | **Data Type** |
| ------------------------- | ------------- |
| Pregnancies               | int64         |
| Glucose                   | int64         |
| BloodPressure             | int64         |
| SkinThickness             | int64         |
| Insulin                   | int64         |
| BMI                       | float64       |
| DiabetesPedigreeFunction  | float64       |
| Age                       | int64         |
| Outcome (Target Variable) | int64         |

#**✨ Insights:**

* Most columns are integer type (int64)

* Two columns (BMI, DiabetesPedigreeFunction) are floating-point (float64)

* The target variable is Outcome (0 = No Diabetes, 1 = Diabetes)

---

#**📊 Statistical Summary (df.describe())**
---

The Pima Indians Diabetes dataset summary statistics:

| Statistic | Pregnancies | Glucose | BloodPressure | SkinThickness | Insulin | BMI   | DiabetesPedigreeFunction | Age   | Outcome |
| --------- | ----------- | ------- | ------------- | ------------- | ------- | ----- | ------------------------ | ----- | ------- |
| **Count** | 768         | 768     | 768           | 768           | 768     | 768   | 768                      | 768   | 768     |
| **Mean**  | 3.85        | 120.89  | 69.11         | 20.54         | 79.80   | 31.99 | 0.47                     | 33.24 | 0.35    |
| **Std**   | 3.37        | 31.97   | 19.36         | 15.95         | 115.24  | 7.88  | 0.33                     | 11.76 | 0.48    |
| **Min**   | 0           | 0       | 0             | 0             | 0       | 0     | 0.078                    | 21    | 0       |
| **25%**   | 1           | 99      | 62            | 0             | 0       | 27.3  | 0.244                    | 24    | 0       |
| **50%**   | 3           | 117     | 72            | 23            | 30.5    | 32.0  | 0.373                    | 29    | 0       |
| **75%**   | 6           | 140.25  | 80            | 32            | 127.25  | 36.6  | 0.626                    | 41    | 1       |
| **Max**   | 17          | 199     | 122           | 99            | 846     | 67.1  | 2.42                     | 81    | 1       |

#**📝 Key Insights**

* ✅ Dataset has 768 samples for each column.

* ⚡ Several features (Glucose, BloodPressure, SkinThickness, Insulin, BMI) contain 0 values, which may represent missing or unrecorded data.

* 🧮 Average age of patients is around 33 years, but max age goes up to 81.

* 🍼 Patients have on average ~4 pregnancies, with a maximum of 17.

* 🩺 The target Outcome shows that ~35% of patients are diabetic (1).

---

#**🔹 df.columns**
---
This shows the names of all columns in your dataset:

* Pregnancies → Number of times pregnant

* Glucose → Plasma glucose concentration

* BloodPressure → Diastolic blood pressure (mm Hg)

* SkinThickness → Triceps skinfold thickness (mm)

* Insulin → 2-Hour serum insulin (mu U/ml)

* BMI → Body Mass Index (weight/height²)

* DiabetesPedigreeFunction → Family history of diabetes (genetic risk)

* Age → Age in years

* Outcome → Target variable (0 = No diabetes, 1 = Diabetes

---

#**🔹 df.shape**
---

Output: (768, 9)

📌** Meaning:**

* 768 rows → number of patients (records) in the dataset

* 9 columns → number of features/variables

---

#**🧹 Kicking Out the Clones**
---
"""

# Count duplicate rows
df.duplicated().sum()

"""#**📊 Check for Duplicate Rows**
---
🔍 df.duplicated() – Returns a Boolean Series showing whether each row is a duplicate of a previous row.

* True → row is a duplicate

* False → row is unique (first occurrence)

#➕ .sum():

 Counts all True values in the Boolean Series, giving the total number of duplicate rows in the dataset.

#🚨 Why it matters:
---
**Duplicate rows can skew analysis or bias machine learning models, so knowing the count helps decide whether to clean them.**

#✅ Summary:
---
**df.duplicated().sum() is a quick way to diagnose dataset duplication and ensure data quality before analysis or modeling.**

#**🩹 Fixing the Gaps**
---
"""

# 🔎 Boolean Series: True = missing, False = not missing
df.isnull().sum()

# 🔎 Boolean Series: True = missing, False = not missing
df['Outcome'].isnull()

# ➕ Counts total missing values in Outcome
df['Outcome'].isnull().sum()

"""#**📊 Check Missing Values in Target Column (Outcome)**
---
🔎 df['Outcome'].isnull() – Checks each cell in the Outcome column for missing values (NaN).

* True → missing

* False → not missing

#➕ .sum():

  Counts all True values.

#**✅ Result:**
---

 0 → There are no missing values in the target column, so it’s ready for modeling.

---

#**📊 NumPy Integer Type**

🔹 np.int64(0) – Creates a NumPy integer with value 0 and type int64.

* Used when operations like .sum() return a NumPy object instead of a plain Python integer.

* Compatible with Pandas and NumPy arrays.

#**📊 Outcome at a Glance**
---
"""

# ------------------------------
# Histogram of Outcome Column
# ------------------------------
# Column to plot
# Number of bins (intervals)
# Bar color
df.hist('Outcome', bins=10, color='skyblue')
plt.title('Distribution of Diabetes Outcomes') # Chart title
plt.xlabel('Outcome (0 = No Diabetes, 1 = Diabetes)') # X-axis label
plt.ylabel('"Number of Patients')  # Y-axis label
plt.grid(color='gray', linestyle='dashdot',linewidth=0.5) # Grid for readability
plt.show()  # Display the histogram
# ✅ Visualizes class distribution: shows how many patients have diabetes (1) vs no diabetes (0)

"""#**✨ Histogram of Outcome Column – Summary**
---
#📊 Purpose:

* To visualize the distribution of the Outcome column in the Pima Indians Diabetes dataset.

* Helps quickly see the class balance between diabetic (1) and non-diabetic (0) patients.

#🔹 Code Components:

* df.hist('Outcome', bins=10, color='skyblue') → Plots a histogram for the Outcome column.

* plt.title(...) → Adds a chart title.

* plt.xlabel(...) & plt.ylabel(...) → Label the x-axis and y-axis for clarity.

* plt.grid(...) → Adds a grid to make it easier to read the values.

* plt.show() → Displays the plot in Colab.

#**✅ Result Interpretation:**
---
* Two bars appear (0 and 1), showing number of patients without diabetes vs with diabetes.

* Useful for detecting class imbalance before modeling.

#**🌌 Feature Face-Offs**
---
"""

# ------------------------------
# Pairplot of Dataset
# ------------------------------
# sns.pairplot(df, hue='Outcome') creates a grid of scatterplots and histograms
# Each variable is plotted against every other variable
# hue='Outcome' colors the points by the target column (0 = No Diabetes, 1 = Diabetes)

sns.pairplot(df, hue='Outcome')

# ------------------------------
# Scatterplot of Pregnancies vs Glucose
# ------------------------------
# sns.scatterplot(...) creates a scatterplot of two variables
# x='Pregnancies' → X-axis shows number of pregnancies
# y='Glucose' → Y-axis shows glucose level
# hue='Outcome' → Colors points based on diabetes outcome (0 = No, 1 = Yes)
# data=df → Use the Pima Indians Diabetes dataset
# palette="coolwarm" → Sets color scheme for classes
# s=80 → Size of the scatterplot markers
sns.scatterplot(x='Pregnancies', y='Glucose', hue= 'Outcome', data=df, palette="coolwarm", s=80)
plt.title('Pregnancies vs Glucose by Outcome')# Add title
plt.show()# Display the scatterplot

# ------------------------------
# Scatterplot of BloodPressure vs SkinThickness
# ------------------------------
# sns.scatterplot(...) creates a scatterplot of two variables
# x='BloodPressure' → X-axis shows blood pressure values
# y='SkinThickness' → Y-axis shows skin thickness measurements
# hue='Outcome' → Colors points based on diabetes outcome (0 = No, 1 = Yes)
# data=df → Use the Pima Indians Diabetes dataset
# palette="YlGnBu" → Sets color scheme for classes
# s=80 → Size of the scatterplot markers
sns.scatterplot(x='BloodPressure', y='SkinThickness',  hue= 'Outcome', data=df, palette="YlGnBu", s=80)
plt.title('BloodPressure vs SkinThickness by Outcome')#Add title
plt.show()# Display the scatterplot

# ------------------------------
# Scatterplot of Insulin vs BMI
# ------------------------------
# sns.scatterplot(...) creates a scatterplot of two variables
# x='Insulin' → X-axis shows insulin levels
# y='BMI' → Y-axis shows Body Mass Index
# hue='Outcome' → Colors points based on diabetes outcome (0 = No, 1 = Yes)
# data=df → Use the Pima Indians Diabetes dataset
# palette="PuOr" → Sets color scheme for classes (purple-orange gradient)
# s=80 → Size of the scatterplot markers
sns.scatterplot(x='Insulin', y='BMI',hue= 'Outcome', data=df, palette="PuOr", s=80)
plt.title('Insulin vs BMI by Outcome')#Add title
plt.show()#Display the scatterplot

# ------------------------------
# Scatterplot of DiabetesPedigreeFunction vs Age
# ------------------------------
# sns.scatterplot(...) creates a scatterplot of two variables
# x='DiabetesPedigreeFunction' → X-axis shows diabetes pedigree function values
# y='Age' → Y-axis shows patient age
# hue='Outcome' → Colors points based on diabetes outcome (0 = No, 1 = Yes)
# data=df → Use the Pima Indians Diabetes dataset
# palette="RdBu" → Sets color scheme for classes (red-to-blue gradient)
# s=80 → Size of the scatterplot markers
sns.scatterplot(x='DiabetesPedigreeFunction', y='Age',hue= 'Outcome', data=df, palette="RdBu", s=80)
plt.title('DiabetesPedigreeFunction vs Age by Outcome')#Add title
plt.show()#Display the scatterplot

"""#**✨ Pairplot Explanation**
---
* import seaborn as sns

* sns.pairplot(df, hue='Outcome')

#**📌 What It Does:**
---
* Creates a matrix of scatterplots for all numerical features.

* Diagonal shows histograms (or density plots) for each variable.

* Off-diagonal shows scatterplots comparing every pair of features.

* hue='Outcome' colors points by target class (0 = non-diabetic, 1 = diabetic).

#**✅ Why It’s Useful:**
---
* Helps detect relationships between features.

* Shows which features separate diabetic and non-diabetic patients.

* Can highlight clusters, overlaps, or correlations between features.

* Useful for feature selection before modeling.

#**✨ Key Features in the Dataset**
---
✨ Key Features in the Dataset

| Feature                        | Meaning                        | What to Look For in Pairplots                                                                 |
|--------------------------------|--------------------------------|------------------------------------------------------------------------------------------------|
| Pregnancies                     | Number of times pregnant       | Higher pregnancies may correlate with diabetes. Look for separation in Outcome classes.       |
| Glucose                         | Plasma glucose concentration   | Higher glucose often correlates with diabetes. Expect diabetic patients to cluster higher.    |
| BloodPressure                   | Diastolic blood pressure       | Look for patterns or correlations with other features like SkinThickness or BMI.              |
| SkinThickness                   | Triceps skin fold thickness    | Can indicate body fat; may correlate with BMI or diabetes risk.                               |
| Insulin                         | 2-Hour serum insulin           | Higher insulin may indicate insulin resistance; check clustering with Outcome.                |
| BMI                             | Body Mass Index                | Higher BMI often correlates with diabetes; look for separation in Outcome.                     |
| DiabetesPedigreeFunction (DPF)  | Genetic predisposition         | Higher values indicate higher diabetes risk; see how it spreads with Age or Glucose.          |
| Age                             | Age of the patient             | Older patients may have higher diabetes risk; observe any trend in scatterplots.              |
| Outcome                         | Target (0 = No Diabetes, 1 = Diabetes) | Coloring in pairplots shows which features discriminate between classes.             |


#**📌 How to Interpret Pairplots for Key Features**
---
* Glucose vs Pregnancies: Diabetic patients often have higher glucose; clustering may appear in scatterplots.

* BMI vs Insulin: Diabetic patients may cluster at higher BMI and insulin levels.

* DPF vs Age: Can show genetic predisposition trends across age groups.

* BloodPressure vs SkinThickness: Look for correlations; may help detect patterns related to obesity or hypertension.

#**✅ Takeaway:**
---
Pairplots provide a visual overview of relationships and can help identify strong predictors of diabetes, detect class separations, and guide feature selection for modeling.

#**🩺 Unveiling Hidden Links: Correlation Heatmap of PIMA Diabetes Dataset**
---
"""

# 📊 Correlation Heatmap for PIMA Indians Diabetes Dataset
# 🎨 Set the figure size for better visibility
plt.figure(figsize=(10,10))
# 🔍 Compute the correlation matrix for all numerical features in the dataset
correlation_matrix = df.corr()
# 🧩 Plot the heatmap with correlation values and a soft pastel color scheme
sns.heatmap(correlation_matrix, annot=True, cmap='Pastel1')
# 🏷️ Add a clear and professional title to the heatmap
plt.title('🩺 Correlation Matrix of PIMA Indians Diabetes Dataset', fontsize=16)
# 👀 Display the heatmap
plt.show()

"""#**Detailed Explanation**
**📊 Correlation Heatmap Explanation**
---
The correlation heatmap is a visual tool that shows how strongly different features of the PIMA Indians Diabetes Dataset are related to each other. It uses colors and numerical values to highlight whether features move together (positive correlation), opposite (negative correlation), or are independent of each other.

**🔹 Correlation values range between -1 and +1:**

 * +1 → A perfect positive relationship (as one feature increases, the other always increases).

 * -1 → A perfect negative relationship (as one feature increases, the other always decreases).

 * 0 → No relationship between the two features.
---
#**🧩 Why It Matters in Diabetes Prediction**
---
Understanding correlations is extremely important in healthcare analytics and machine learning because:

 * It helps to detect multicollinearity (when two predictors provide the same information).

 * It identifies key health factors that are most linked to diabetes risk.

 * It guides feature selection, so we can choose the most relevant predictors when building models.

 * It provides clinical insights, showing which health measures (e.g., glucose, BMI) have the strongest links to diabetes outcomes.
---
#**💡 Dataset-Specific Insights**
---
From the heatmap of the PIMA dataset, several important patterns appear:

 * Glucose → Shows the strongest positive correlation with the diabetes outcome. This aligns with medical knowledge, since higher blood glucose is directly associated with diabetes diagnosis.

 * BMI (Body Mass Index) → Has a clear positive correlation with the outcome, suggesting that obesity is a strong risk factor.

 * Age → Older individuals show a higher likelihood of diabetes, though the correlation is moderate.

 * Pregnancies → Has a moderate correlation, showing that women with more pregnancies may be more prone to developing diabetes.

* Insulin & Skin Thickness → These features have weaker direct correlations, but may still carry value when combined with other predictors.

* Blood Pressure → Shows very low correlation, meaning it may not be a strong standalone predictor but could still contribute in interaction with other features.
---
#**📌 Conclusion**
---
The heatmap reveals that Glucose and BMI are the most important predictors of diabetes in this dataset, while Age and Pregnancies provide additional demographic context. Features like Blood Pressure, Insulin, and Skin Thickness are less directly correlated but should not be ignored, as they may enhance prediction when used alongside stronger predictors.

This visualization is a crucial first step in data analysis, helping us decide which features to prioritize for building machine learning models and also giving clinical meaning to the dataset.

#**📈 Machine Learning: From Data to Predictions**
---

#**Best Models For Project**
---
"""

# 📌 1. Import Libraries
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

# 📌 2. Load Dataset
df = pd.read_csv('/content/diabetes csv')  # Change path if needed

# 📌 3. Encode Categorical Columns (if any)
label_enc = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = label_enc.fit_transform(df[col])

# 📌 4. Define Features (X) & Target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# 📌 5. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 📌 6. Feature Scaling (important for SVM, KNN, Logistic Regression)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 📌 7. Define Models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(probability=True)
}

# 📌 8. Train, Predict & Evaluate
results = []

for name, model in models.items():
    start = time.time()
    model.fit(X_train, y_train)  # Training
    y_pred = model.predict(X_test)  # Prediction
    y_proba = model.predict_proba(X_test)[:, 1]  # Probability for ROC-AUC
    end = time.time()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC-AUC": roc_auc_score(y_test, y_proba),
        "Speed (s)": round(end - start, 4)
    })

# 📌 9. Show Results Table
results_df = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False)
results_df = results_df.round(4)  # Round values for clean output
print("\n📊 Model Comparison:\n")
print(results_df)

# 📌 10. Bar Chart Comparison
results_df.set_index("Model")[["Accuracy", "F1 Score", "ROC-AUC"]].plot(
    kind="bar", figsize=(10, 6), rot=45
)
plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.show()

# 📌 11. Detailed Report for Best Model
best_model_name = results_df.iloc[0]["Model"]
print(f"\n✅ Best Model: {best_model_name}\n")
best_model = models[best_model_name]
y_pred_best = best_model.predict(X_test)
print(classification_report(y_test, y_pred_best))

# 📌 12. Final Summary
print(f"🔹 {best_model_name} achieved Accuracy = {results_df.iloc[0]['Accuracy']:.2f}, "
      f"F1 = {results_df.iloc[0]['F1 Score']:.2f}, "
      f"Speed = {results_df.iloc[0]['Speed (s)']}s")

# =============================
# Imports
# =============================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, roc_curve, auc, precision_recall_curve
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

# =============================
# Load Dataset
# =============================
# Example: df = pd.read_csv("diabetes.csv")
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# =============================
# Balance Dataset with SMOTE
# =============================
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X, y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =============================
# Model: Random Forest
# =============================
rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_pred_proba = rf.predict_proba(X_test)[:, 1]

# ✅ Metrics (no F1)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("✅ Random Forest Accuracy:", accuracy)
print("🎯 Precision:", precision)
print("🔄 Recall:", recall)

# =============================
# 🔥 Plots
# =============================

# 1. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues",
            xticklabels=["No Diabetes","Diabetes"],
            yticklabels=["No Diabetes","Diabetes"])
plt.title("Confusion Matrix", fontsize=14)
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.show()

# 2. ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, color="darkorange", lw=2, label="ROC Curve (AUC = %0.2f)" % roc_auc)
plt.plot([0,1], [0,1], color="navy", lw=2, linestyle="--")
plt.title("ROC Curve", fontsize=14)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend(loc="lower right")
plt.show()

# 3. Precision-Recall Curve
precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_pred_proba)
plt.figure(figsize=(6,5))
plt.plot(recall_vals, precision_vals, color="green", lw=2)
plt.title("Precision-Recall Curve", fontsize=14)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

# 4. Feature Importance
rf_importances = pd.Series(rf.feature_importances_, index=df.drop('Outcome', axis=1).columns)

plt.figure(figsize=(8,6))
rf_importances.sort_values().plot(kind="barh", color="skyblue")
plt.title("Random Forest Feature Importances")
plt.show()

# ------------------------- #
# 📊 PLOTS SECTION (extra)
# ------------------------- #

# 1) Distribution plots of key features
key_features = ["Glucose", "BMI", "Age", "BloodPressure"]
for feature in key_features:
    plt.figure(figsize=(6,4))
    sns.histplot(data=df, x=feature, hue="Outcome", kde=True, bins=30, palette="coolwarm")
    plt.title(f"Distribution of {feature} by Outcome")
    plt.xlabel(feature)
    plt.ylabel("Count")
    plt.show()

# 2) Confusion Matrix Heatmap
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["No Diabetes", "Diabetes"],
            yticklabels=["No Diabetes", "Diabetes"])
plt.title("Confusion Matrix Heatmap")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# 3) Precision & Recall Bar Plot
plt.figure(figsize=(5,4))
metrics = {"Accuracy": accuracy, "Precision": precision, "Recall": recall}
sns.barplot(x=list(metrics.keys()), y=list(metrics.values()), palette="viridis")
plt.title("Evaluation Metrics (No F1)")
plt.ylim(0,1)
plt.show()

"""#**📘 Random Forest Diabetes Prediction – Explanation**
---
**1️⃣ Imports**

* We begin by importing required libraries:

* Data Preprocessing: train_test_split, StandardScaler

*  Evaluation Metrics: accuracy_score, precision_score, recall_score

*  Model: RandomForestClassifier

*  Balancing Data: SMOTE
---
#**2️⃣ Load Dataset**
X = df.drop('Outcome', axis=1)   # Features

y = df['Outcome']                # Target


X → Independent variables (e.g., Glucose, BMI, Age).

y → Dependent variable (Outcome: 1 = Diabetes, 0 = No Diabetes).

---

#**3️⃣ Handle Class Imbalance (SMOTE)**
---
*  sm = SMOTE(random_state=42)

*  X_res, y_res = sm.fit_resample(X, y)


*  If diabetic patients are fewer than non-diabetic, the model becomes biased.

*  SMOTE creates synthetic diabetic cases so the dataset becomes balanced.

---

#**4️⃣ Train-Test Split**
---
X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.2, random_state=42
)


* 80% training data → used to train the model.

* 20% testing data → used to evaluate on unseen data.

---

#**5️⃣ Feature Scaling**

* scaler = StandardScaler()
* X_train = scaler.fit_transform(X_train)
* X_test = scaler.transform(X_test)


Standardizes all features to have:

Mean = 0, Standard Deviation = 1

Mean=0,Standard Deviation=1

Prevents large-value features (like Age) from dominating.

---

#**6️⃣ Random Forest Model**

rf = RandomForestClassifier(

    n_estimators=500,
    max_depth=None,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)


Random Forest builds multiple decision trees and combines their outputs.

Parameters:

* n_estimators=500 → number of trees.

* class_weight="balanced" → handles imbalance.

* n_jobs=-1 → uses all CPU cores.

---

#**7️⃣ Predictions**
---
* y_pred = rf.predict(X_test)

* y_pred_proba = rf.predict_proba(X_test)[:, 1]


* y_pred → final predicted class (0 or 1).

* y_pred_proba → probability of diabetes (used in ROC & PR curves).

---

#**8️⃣ Evaluation Metrics**
---
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)


* Accuracy: Overall correctness.

* Precision: Of all patients predicted diabetic, how many truly are.

* Recall (Sensitivity): Of all actual diabetic patients, how many were caught.

**✅ Example Results:**

* Accuracy = 82.5%

* Precision = 78%

* Recall = 91%

---

#**9️⃣ Visualizations**
---
We use multiple plots to interpret the model:

Confusion Matrix → Shows correct & incorrect predictions.

ROC Curve & AUC → Trade-off between sensitivity & false positives.

Precision-Recall Curve → Balance between precision & recall.

Feature Importance → Which features (Glucose, BMI, Age, etc.) matter most.

Feature Distributions → Histograms for Glucose, BMI, Age by diabetes outcome.

---

#**✅ Conclusion:**
---
* The model has high recall (91%) → excellent at detecting diabetic patients.

* Precision (78%) → some false alarms, but acceptable in healthcare (better to over-warn than to miss).

* Overall accuracy = 82.5%, which is strong for this dataset.
---

#**Summary**
---
DiaDecode Notebook Analysis

Introduction and Objective

The notebook analyzes the Pima Indians Diabetes dataset to explore and predict diabetes risk using machine learning. It describes the dataset features (such as glucose level, BMI, age, etc.) and explicitly states that the goal is “prediction of diabetes likelihood based on simple but meaningful diagnostic measurements”. The authors outline a workflow of cleaning the data, performing exploratory data analysis (EDA), and training various classification models to identify the most predictive factors.

Data Loading and Overview

The dataset (768 records, 9 columns) is loaded from a CSV file into a Pandas DataFrame. A quick check shows its shape as (768, 9). All features are numeric (7 integers, 2 floats) and there are no missing values reported in any column. The notebook explicitly checks for duplicates (df.duplicated().sum()) and finds 0 duplicate rows. In summary, the raw data is clean: each column has 768 non-null entries and no immediate cleaning (like dropping NaNs) is needed.

Exploratory Data Analysis

Dataset Preview: The first and last few rows of the data are shown (via df.head() and df.tail()) along with a description of each feature (pregnancies, glucose, blood pressure, etc.). The markdown tables indicate both diabetic (Outcome=1) and non-diabetic cases appear throughout.

Summary Statistics: Using df.describe(), the notebook notes that several features (Glucose, BloodPressure, SkinThickness, Insulin, BMI) contain 0 values. These zeros likely represent missing or unrecorded measurements. For instance, it remarks: “Several features … contain 0 values, which may represent missing or unrecorded data.”. The distribution of the target is also observed: about 35% of patients are diabetic (Outcome=1). (This is inferred from summary insights, and a histogram is plotted to confirm class balance.)

Outcome Distribution: A histogram of the Outcome column is plotted to check class balance. The plot shows two bars (0 and 1) indicating counts of non-diabetic vs. diabetic patients. The notebook notes that this helps “quickly see the class balance” and that two bars appear for the two classes. In this dataset, the diabetic class is smaller (roughly one-third of patients).

Pairplot of Features: The authors generate a seaborn pairplot (sns.pairplot(df, hue='Outcome')) to visualize pairwise relationships among all features, colored by diabetes outcome. This creates a grid of scatterplots and histograms (72 subplots for 9 features). The pairplot helps reveal patterns, for example, whether diabetic vs. non-diabetic patients cluster differently along combinations like Glucose vs. BMI. The notebook’s explanation notes that a pairplot “creates a matrix of scatterplots for all numerical features” with coloring by the target class.

Correlation Heatmap: A correlation matrix heatmap is computed and displayed. The notebook describes it as a visual tool showing feature inter-relationships. In particular, the text points out that Glucose and BMI have the strongest positive correlations with the diabetes outcome, reflecting their importance as risk factors. (For example: “Glucose shows the strongest positive correlation with the diabetes outcome… BMI has a clear positive correlation…”.) Other features like Age and Pregnancies have moderate correlation, while Insulin, SkinThickness, and BloodPressure are weaker predictors according to this heatmap analysis.

Machine Learning Modeling
Models Compared: The dataset is split into training/test sets (80/20), and features are scaled. The notebook defines and trains several classifiers: Logistic Regression, Decision Tree, Random Forest, Gradient Boosting, K-Nearest Neighbors, Naive Bayes, and SVM. Each model’s accuracy, precision, recall, F1, and ROC-AUC are computed on the test set.

Model Comparison Results: A summary table of model performance is printed and visualized (bar chart). The output table shows Gradient Boosting and SVM both achieving the highest accuracy (~0.753) on the test data, followed by Random Forest (0.747). For example, Gradient Boosting has Accuracy=0.7532, and SVM also 0.7532. The notebook then identifies Gradient Boosting as the “Best Model” (since it tied for highest accuracy) and prints its classification report.

Random Forest Analysis: Despite Gradient Boosting being top-scoring, the notebook presents a detailed example using Random Forest. The RandomForestClassifier (with 500 trees and balanced class weights) is trained, and key metrics are printed. The Random Forest achieves Accuracy = 0.825, with precision ≈0.780 and recall ≈0.911. (Precision, recall, etc. indicate strong performance on detecting diabetic cases.) The code also plots the confusion matrix, ROC curve, precision-recall curve, and computes feature importances (bar chart). These visualizations are used to further assess the Random Forest model (e.g. showing its ROC-AUC and which features were most important).
Results and Conclusions

In summary, the notebook’s key findings are:

Data Insights: The Pima dataset has 768 cases with no missing values. There is class imbalance (65% non-diabetic vs. 35% diabetic) as shown in the outcome histogram. Some features contain zero values that likely indicate missing data (especially Insulin and SkinThickness).
Predictive Models: Among the models tested, Gradient Boosting and SVM achieved the highest test accuracy (75%). The notebook ultimately focuses on Random Forest for illustration. The Random Forest classifier attained about 82.5% accuracy on the test set, with high recall (indicating it catches most diabetics). Feature importance plots (not numerically cited) likely show that glucose level and BMI are among the strongest predictors.

Overall Purpose: The DiaDecode notebook serves as a structured demonstration of how to “clean and preprocess data, perform EDA, and train ML models” for diabetes prediction. It concludes that the glucose and BMI features are highly indicative of diabetes (as seen in the heatmap discussion) and that ensemble models (Gradient Boosting, Random Forest) perform well on this task (achieving ~75–82% accuracy).
Sources: Excerpts are drawn directly from the notebook’s markdown and output cells to verify the dataset content, code steps, and reported metrics. The notebook’s explanatory text and visualizations guide the analysis as summarized above.
"""